package com.example.sqltest.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;
import java.util.Date;
import java.io.InputStream;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Fri Mar 29 16:56:50 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_de_model" )
public class ActDeModelBean  implements Serializable {

	@Id
   	@Column(name = "id" )
	private String id;

   	@Column(name = "name" )
	private String name;

   	@Column(name = "model_key" )
	private String modelKey;

   	@Column(name = "description" )
	private String description;

   	@Column(name = "model_comment" )
	private String modelComment;

   	@Column(name = "created" )
	private Date created;

   	@Column(name = "created_by" )
	private String createdBy;

   	@Column(name = "last_updated" )
	private Date lastUpdated;

   	@Column(name = "last_updated_by" )
	private String lastUpdatedBy;

   	@Column(name = "version" )
	private Long version;

   	@Column(name = "model_editor_json" )
	private String modelEditorJson;

   	@Column(name = "model_type" )
	private Long modelType;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getModelKey() {
		return this.modelKey;
	}

	public void setModelKey(String modelKey) {
		this.modelKey = modelKey;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getModelComment() {
		return this.modelComment;
	}

	public void setModelComment(String modelComment) {
		this.modelComment = modelComment;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getLastUpdated() {
		return this.lastUpdated;
	}

	public void setLastUpdated(Date lastUpdated) {
		this.lastUpdated = lastUpdated;
	}

	public String getLastUpdatedBy() {
		return this.lastUpdatedBy;
	}

	public void setLastUpdatedBy(String lastUpdatedBy) {
		this.lastUpdatedBy = lastUpdatedBy;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getModelEditorJson() {
		return this.modelEditorJson;
	}

	public void setModelEditorJson(String modelEditorJson) {
		this.modelEditorJson = modelEditorJson;
	}

	public Long getModelType() {
		return this.modelType;
	}

	public void setModelType(Long modelType) {
		this.modelType = modelType;
	}

}
