package com.example.sqltest.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Tue Mar 12 11:22:44 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_id_membership" )
public class ActIdMembershipBean  implements Serializable {


	private static final long serialVersionUID =  7212128410004749284L;


   	@Column(name = "USER_ID_" )
	private String userId;

   	@Column(name = "GROUP_ID_" )
	private String groupId;

	public String getUserId() {
		return this.userId;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

}
