package com.example.sqltest.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Tue Mar 12 11:22:44 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_id_membership" )
public class ActIdMembershipBean  implements Serializable {

	@Id
   	@Column(name = "USER_ID_" )
	private String userName;

   	@Column(name = "GROUP_ID_" )
	private String groupId;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

}
