package com.example.sqltest.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Tue Mar 12 11:22:34 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_id_group" )
public class ActIdGroupBean  implements Serializable {


	private static final long serialVersionUID =  6510074593000287728L;


   	@Column(name = "ID_" )
	private String id;

   	@Column(name = "REV_" )
	private Long rev;

   	@Column(name = "NAME_" )
	private String name;

   	@Column(name = "TYPE_" )
	private String type;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getRev() {
		return this.rev;
	}

	public void setRev(Long rev) {
		this.rev = rev;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
