package com.example.sqltest.bean;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Mar 07 15:07:47 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_id_user" )
public class ActivitiUserBean implements Serializable {

	@Id
   	@Column(name = "ID_" )
	private String userName;

   	@Column(name = "REV_" )
	private Long rev;

   	@Column(name = "FIRST_" )
	private String firstName;

   	@Column(name = "LAST_" )
	private String lastName;

   	@Column(name = "EMAIL_" )
	private String email;

   	@Column(name = "PWD_" )
	private String password;

   	@Column(name = "PICTURE_ID_" )
	private String pictureId;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public Long getRev() {
		return rev;
	}

	public void setRev(Long rev) {
		this.rev = rev;
	}

	public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPictureId() {
		return pictureId;
	}

	public void setPictureId(String pictureId) {
		this.pictureId = pictureId;
	}
}
