package com.example.sqltest.bean;

import javax.persistence.*;
import java.io.Serializable;
import java.util.Date;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Thu Mar 28 16:05:09 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_re_deployment" )
public class ActReDeploymentBean  implements Serializable {

	@Id
   	@Column(name = "ID_" )
	private String id;

   	@Column(name = "NAME_" )
	private String name;

   	@Column(name = "CATEGORY_" )
	private String category;

   	@Column(name = "KEY_" )
	private String key;

   	@Column(name = "TENANT_ID_" )
	private String tenantId;

   	@Column(name = "DEPLOY_TIME_" )
	private Date deployTime;

   	@Column(name = "ENGINE_VERSION_" )
	private String engineVersion;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public Date getDeployTime() {
		return this.deployTime;
	}

	public void setDeployTime(Date deployTime) {
		this.deployTime = deployTime;
	}

	public String getEngineVersion() {
		return this.engineVersion;
	}

	public void setEngineVersion(String engineVersion) {
		this.engineVersion = engineVersion;
	}

}
