package com.example.sqltest.bean;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import java.io.Serializable;

/**
 * generated by Generate POJOs.groovy 
 * <p>Date: Mon Apr 01 15:30:44 GMT+08:00 2019.</p>
 *
 * @author T016
 */

@Entity
@Table ( name ="act_re_procdef" )
public class ActReProcdefBean  implements Serializable {

	@Id
   	@Column(name = "ID_" )
	private String id;

   	@Column(name = "REV_" )
	private Long rev;

   	@Column(name = "CATEGORY_" )
	private String category;

   	@Column(name = "NAME_" )
	private String name;

   	@Column(name = "KEY_" )
	private String key;

   	@Column(name = "VERSION_" )
	private Long version;

   	@Column(name = "DEPLOYMENT_ID_" )
	private String deploymentId;

   	@Column(name = "RESOURCE_NAME_" )
	private String resourceName;

   	@Column(name = "DGRM_RESOURCE_NAME_" )
	private String dgrmResourceName;

   	@Column(name = "DESCRIPTION_" )
	private String description;

   	@Column(name = "HAS_START_FORM_KEY_" )
	private Integer hasStartFormKey;

   	@Column(name = "HAS_GRAPHICAL_NOTATION_" )
	private Integer hasGraphicalNotation;

   	@Column(name = "SUSPENSION_STATE_" )
	private Long suspensionState;

   	@Column(name = "TENANT_ID_" )
	private String tenantId;

   	@Column(name = "ENGINE_VERSION_" )
	private String engineVersion;

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Long getRev() {
		return this.rev;
	}

	public void setRev(Long rev) {
		this.rev = rev;
	}

	public String getCategory() {
		return this.category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getKey() {
		return this.key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public Long getVersion() {
		return this.version;
	}

	public void setVersion(Long version) {
		this.version = version;
	}

	public String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(String deploymentId) {
		this.deploymentId = deploymentId;
	}

	public String getResourceName() {
		return this.resourceName;
	}

	public void setResourceName(String resourceName) {
		this.resourceName = resourceName;
	}

	public String getDgrmResourceName() {
		return this.dgrmResourceName;
	}

	public void setDgrmResourceName(String dgrmResourceName) {
		this.dgrmResourceName = dgrmResourceName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Integer getHasStartFormKey() {
		return this.hasStartFormKey;
	}

	public void setHasStartFormKey(Integer hasStartFormKey) {
		this.hasStartFormKey = hasStartFormKey;
	}

	public Integer getHasGraphicalNotation() {
		return this.hasGraphicalNotation;
	}

	public void setHasGraphicalNotation(Integer hasGraphicalNotation) {
		this.hasGraphicalNotation = hasGraphicalNotation;
	}

	public Long getSuspensionState() {
		return this.suspensionState;
	}

	public void setSuspensionState(Long suspensionState) {
		this.suspensionState = suspensionState;
	}

	public String getTenantId() {
		return this.tenantId;
	}

	public void setTenantId(String tenantId) {
		this.tenantId = tenantId;
	}

	public String getEngineVersion() {
		return this.engineVersion;
	}

	public void setEngineVersion(String engineVersion) {
		this.engineVersion = engineVersion;
	}

}
